### ISSUE TITLE
Add unit tests to GitHub actions

### ISSUE THREAD

**Issue by bjornthiberg** [group19-se24/assignment-2#16]
We are recommended to use a normal CI service in this assignment. The current GitHub action only compiles the code. It should also run the JUnit tests.

**Comment by bjornthiberg** [comment]
`mvn package` should run tests as well, but it does not seem like they are being run.

**Comment by Oozna** [comment]
Don't forget that we need to ensure that it has MySQL and the GITHUB_TOKEN env set.

**Comment by bjornthiberg** [comment]
Not necessary.
