### ISSUE TITLE
Add functionality to clone repository on push event

### ISSUE THREAD

**Issue by bjornthiberg** [group19-se24/assignment-2#3]

**Comment by samshahriari** [comment]
- [ ] Download a specific repo into temp folder
- [ ] The repo downloaded should be the one specified in the web hook
- [ ] Switch to the correct branch

**Comment by samshahriari** [comment]
"ref": "refs/heads/6-add-functionality-to-save-build-history", gives the current branch

**Comment by samshahriari** [comment]
"git_url": "git://github.com/group19-se24/assignment-2.git",

gives url
